permalink: /:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
paginate: 12
gems: ["jekyll-prism-plugin"]

title : Cymen Vig
url: http://blog.cymen.org
tagline: Software Craftsman
author :
  name : Cymen Vig
  email : cymenvig@gmail.com
  github : cymen
  twitter : cymen
  instagram: cym3n
  flickr: cymen
  feedburner : CymensBlog

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://blog.cymen.org
